name: fluviewer
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bbmap=39.01
  - bcftools=1.17
  - blast=2.14.1
  - bwa=0.7.17
  - samtools=1.17
  - spades=4.0.0
  - clustalw=2.1
  - freebayes=1.3.6
  - python=3
  - pip
  - pandas=2.0.3
  - seaborn=0.12.2
  - pip:
    - git+https://github.com/BCCDC-PHL/FluViewer.git@v0.1.11-3
