name: fluviewer
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bbmap=39.01
  - bcftools=1.17
  - blast=2.14.1
  - bwa=0.7.17
  - samtools=1.17
  - spades=3.15.3
  - ncbi-vdb=3.0.6
  - pandas=2.0.3
  - seaborn=0.12.2
