name: fluviewer-kkuchinski
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bbmap=39.01
  - bcftools=1.17
  - blast=2.14.1
  - bwa=0.7.17
  - samtools=1.17
  - spades=3.15.3
  - clustalw=2.1
  - freebayes=1.3.6
  - python=3.9
  - setuptools=69
  - pip
  - pandas=2.0
  - seaborn=0.12
  - pip:
    - FluViewer==0.1.11
